# Generated by Django 4.0.6 on 2023-08-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-price'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
